package svg_test

import (
	"testing"

	"github.com/flowdev/gflowparser/svg"
)

const expSVG = `<?xml version="1.0" ?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="826px" height="599px">
<!-- Generated by simple FlowDev draw-svg tool. -->
	<rect fill="rgb(255,255,255)" fill-opacity="1" stroke="none" stroke-opacity="1" stroke-width="0.0" width="826" height="599" x="0" y="0"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="26" y1="25" x2="116" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="108" y1="17" x2="116" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="108" y1="33" x2="116" y2="25"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="212" y1="25" x2="362" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="354" y1="17" x2="362" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="354" y1="33" x2="362" y2="25"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="530" y1="25" x2="704" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="17" x2="704" y2="25"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="33" x2="704" y2="25"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="212" y1="232" x2="314" y2="232"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="306" y1="224" x2="314" y2="232"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="306" y1="240" x2="314" y2="232"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="410" y1="232" x2="512" y2="232"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="504" y1="224" x2="512" y2="232"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="504" y1="240" x2="512" y2="232"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="38" y1="313" x2="104" y2="313"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="96" y1="305" x2="104" y2="313"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="96" y1="321" x2="104" y2="313"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="200" y1="313" x2="704" y2="313"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="305" x2="704" y2="313"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="321" x2="704" y2="313"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="38" y1="394" x2="140" y2="394"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="132" y1="386" x2="140" y2="394"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="132" y1="402" x2="140" y2="394"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="308" y1="394" x2="704" y2="394"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="386" x2="704" y2="394"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" x1="696" y1="402" x2="704" y2="394"/>

	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="96" height="277" x="116" y="7" rx="10" ry="10"/>
	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="190" x="362" y="7" rx="10" ry="10"/>
	<rect fill="rgb(32,224,32)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="57" x="362" y="43"/>
	<rect fill="rgb(32,224,32)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="84" x="362" y="100"/>
	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="96" height="64" x="314" y="214" rx="10" ry="10"/>
	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="96" height="64" x="104" y="295" rx="10" ry="10"/>
	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="214" x="140" y="376" rx="10" ry="10"/>
	<rect fill="rgb(32,224,32)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="57" x="140" y="436"/>
	<rect fill="rgb(32,224,32)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="168" height="84" x="140" y="493"/>
	<rect fill="rgb(96,196,255)" fill-opacity="1.0" stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="2.5" width="120" height="417" x="704" y="7" rx="10" ry="10"/>

	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="362" y1="70" x2="530" y2="70"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="362" y1="127" x2="530" y2="127"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="362" y1="154" x2="530" y2="154"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="140" y1="463" x2="308" y2="463"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="140" y1="520" x2="308" y2="520"/>
	<line stroke="rgb(0,0,0)" stroke-opacity="1.0" stroke-width="1.0" x1="140" y1="547" x2="308" y2="547"/>

	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="3" y="31" textLength="22" lengthAdjust="spacingAndGlyphs">in</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="41" y="17" textLength="48" lengthAdjust="spacingAndGlyphs">Data</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="128" y="31" textLength="24" lengthAdjust="spacingAndGlyphs">ra</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="128" y="55" textLength="72" lengthAdjust="spacingAndGlyphs">(MiSo)</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="218" y="45" textLength="84" lengthAdjust="spacingAndGlyphs">special</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="257" y="17" textLength="48" lengthAdjust="spacingAndGlyphs">Data</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="326" y="45" textLength="24" lengthAdjust="spacingAndGlyphs">in</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="374" y="31" textLength="24" lengthAdjust="spacingAndGlyphs">do</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="368" y="64" textLength="120" lengthAdjust="spacingAndGlyphs">semantics:</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="368" y="91" textLength="156" lengthAdjust="spacingAndGlyphs">TextSemantics</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="368" y="121" textLength="120" lengthAdjust="spacingAndGlyphs">subParser:</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="368" y="148" textLength="144" lengthAdjust="spacingAndGlyphs">LitralParser</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="368" y="175" textLength="156" lengthAdjust="spacingAndGlyphs">NaturalParser</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="536" y="45" textLength="36" lengthAdjust="spacingAndGlyphs">out</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="545" y="17" textLength="132" lengthAdjust="spacingAndGlyphs">BigDataType</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="656" y="45" textLength="36" lengthAdjust="spacingAndGlyphs">in1</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="218" y="252" textLength="36" lengthAdjust="spacingAndGlyphs">out</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="233" y="224" textLength="48" lengthAdjust="spacingAndGlyphs">Data</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="278" y="252" textLength="24" lengthAdjust="spacingAndGlyphs">in</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="326" y="238" textLength="36" lengthAdjust="spacingAndGlyphs">bla</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="326" y="262" textLength="72" lengthAdjust="spacingAndGlyphs">(Blue)</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="425" y="224" textLength="60" lengthAdjust="spacingAndGlyphs">Data2</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="515" y="238" textLength="34" lengthAdjust="spacingAndGlyphs">...</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="3" y="319" textLength="34" lengthAdjust="spacingAndGlyphs">...</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="68" y="333" textLength="24" lengthAdjust="spacingAndGlyphs">in</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="116" y="319" textLength="36" lengthAdjust="spacingAndGlyphs">bla</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="116" y="343" textLength="72" lengthAdjust="spacingAndGlyphs">(Blue)</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="206" y="333" textLength="36" lengthAdjust="spacingAndGlyphs">out</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="422" y="305" textLength="48" lengthAdjust="spacingAndGlyphs">Data</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="656" y="333" textLength="36" lengthAdjust="spacingAndGlyphs">in2</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="3" y="400" textLength="34" lengthAdjust="spacingAndGlyphs">in2</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="53" y="386" textLength="60" lengthAdjust="spacingAndGlyphs">Data3</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="104" y="414" textLength="24" lengthAdjust="spacingAndGlyphs">in</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="152" y="400" textLength="120" lengthAdjust="spacingAndGlyphs">megaParser</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="152" y="424" textLength="144" lengthAdjust="spacingAndGlyphs">(MegaParser)</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="146" y="457" textLength="120" lengthAdjust="spacingAndGlyphs">semantics:</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="146" y="484" textLength="156" lengthAdjust="spacingAndGlyphs">TextSemantics</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="146" y="514" textLength="120" lengthAdjust="spacingAndGlyphs">subParser:</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="146" y="541" textLength="144" lengthAdjust="spacingAndGlyphs">LitralParser</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="146" y="568" textLength="156" lengthAdjust="spacingAndGlyphs">NaturalParser</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="314" y="414" textLength="36" lengthAdjust="spacingAndGlyphs">out</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="476" y="386" textLength="48" lengthAdjust="spacingAndGlyphs">Data</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="656" y="414" textLength="36" lengthAdjust="spacingAndGlyphs">in3</text>
	<text fill="rgb(0,0,0)" fill-opacity="1.0" font-family="monospace" font-size="16" x="716" y="31" textLength="96" lengthAdjust="spacingAndGlyphs">BigMerge</text>
</svg>
`

func TestFromFlowData(t *testing.T) {
	testFlow := svg.BigTestFlowData

	gotBytes, gotErr := svg.FromFlowData(testFlow)

	if gotErr != nil {
		t.Fatalf("Unexpected error: %s", gotErr)
	}
	if expSVG != string(gotBytes) {
		t.Errorf("Got unexpected SVG:\n%s", string(gotBytes))
	}
}
